name: Run Selenium Pytest
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code from github
        uses: actions/checkout@v4

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install necessary libraries
        run:
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Install Chrome libary
        uses: browser-actions/setup-chrome@1
      
      - name: Create a test report Folder
        run: mkdir -p report
      
      - name: Run Test
        run: pytest -m smoke --html=report/report.html --sefl-contained-html
      
      - name: Upload file report
        if: always()
        uses: action/upload-artifact@v4
        with:
          name: pytest-report 
          path: report/report.html